sudo: required
cache:
  directories:
    - $HOME/.m2
language: java
jdk:
  - oraclejdk8
install: true
script:
  - '[ "${TRAVIS_PULL_REQUEST}" != "false" ] || ./mvnw package -Pfull -U -Dmaven.test.redirectTestOutputToFile=t
rue'
  - '[ "${TRAVIS_PULL_REQUEST}"  = "false" ] || ./mvnw package -Pfull -U -Dmaven.test.redirectTestOutputToFile=t
rue'

after_success:
  - bash <(curl -s https://codecov.io/bash)
