apiVersion: skipper/v1
kind: SpringBootApp
metadata:
  {{#metadata.entrySet}}
  {{key}}: {{value}}
  {{/metadata.entrySet}}
spec:
  resource: {{spec.resource}}:{{version}}
  resourceMetadata: {{spec.resource}}:jar:metadata:{{version}}
  applicationProperties:
    {{#spec.applicationProperties.entrySet}}
    {{key}}: {{value}}
    {{/spec.applicationProperties.entrySet}}
  deploymentProperties:
    {{#spec.deploymentProperties.entrySet}}
    {{key}}: {{value}}
    {{/spec.deploymentProperties.entrySet}}