apiVersion: v1
kind: Application
deployment:
  name: {{deployment.name}}
  count: {{deployment.count}}
  applicationProperties:
    {{#deployment.applicationProperties.entrySet}}
    {{key}}: {{value}}
    {{/deployment.applicationProperties.entrySet}}
  resource: {{deployment.resource}}
  deploymentProperties:
    {{#deployment.deploymentProperties.entrySet}}
    {{key}}: {{value}}
    {{/deployment.deploymentProperties.entrySet}}
